### ISSUE TITLE
ZeroDivisionError in docker_stat_memory with non-running containers

### ISSUE THREAD

**Issue by paulrm** [atommaki/munin-plugin-docker#1]
Hello I found this error in the condition that aren't containers running 

```
/etc/munin/plugins/docker_stat_memory
Traceback (most recent call last):
  File "/etc/munin/plugins/docker_stat_memory", line 139, in <module>
    print(get_munin_values())
  File "/etc/munin/plugins/docker_stat_memory", line 109, in get_values_memory
    f"total.value {sum(memory_usage)}\n"
ZeroDivisionError: division by zero
```

**Comment by atommaki** [comment]
Fixed, script works now without any running containers.
