### ISSUE TITLE
docker_stat_memory error (KeyError: 'rss')

### ISSUE THREAD

**Issue by paulrm** [atommaki/munin-plugin-docker#2]
Hello, testing with:

- CentOS Linux 7 (Core)
- python3-3.6.8-10
- docker (4.2.0)

runing /etc/munin/plugins/docker_stat_memory
```
Traceback (most recent call last):
  File "/etc/munin/plugins/docker_stat_memory", line 140, in <module>
    print(get_munin_values())
  File "/etc/munin/plugins/docker_stat_memory", line 108, in get_values_memory
    memory_usage.append(int(container.stats(stream=False)["memory_stats"]["stats"]["rss"]))
KeyError: 'rss'
```

Looks like container.stats(stream=False) is returning 'memory_stats': {},

**Comment by atommaki** [comment]
I couldn't reproduce it yet. Is it happened once for you or it is still like that?

**Comment by atommaki** [comment]
When you see the issue again, pls open a `python3` shell, run the following and  copy&paste the result here.

```
import docker
client = docker.from_env()
for container in client.containers.list(False):
    print(f" =================== { container.name } ===================")
    print(container.stats(stream=False))
```

**Comment by kmajzlik** [comment]
Just installed your plugin and have exactly same problem.
EDIT: Ubuntu 22.04, Docker version 20.10.22, build 3a2c30b

Here is one container from result of debug you wanted:

```
=================== nginx-proxy ===================
{
   "read":"2023-01-27T12:27:39.583115289Z",
   "preread":"2023-01-27T12:27:38.570067444Z",
   "pids_stats":{
      "current":28,
      "limit":18658
   },
   "blkio_stats":{
      "io_service_bytes_recursive":[
         {
            "major":8,
            "minor":0,
            "op":"read",
            "value":4759552
         },
         {
            "major":8,
            "minor":0,
            "op":"write",
            "value":5287936
         },
         {
            "major":8,
            "minor":16,
            "op":"read",
            "value":42635264
         },
         {
            "major":8,
            "minor":16,
            "op":"write",
            "value":4096
         }
      ],
      "io_serviced_recursive":"None",
      "io_queue_recursive":"None",
      "io_service_time_recursive":"None",
      "io_wait_time_recursive":"None",
      "io_merged_recursive":"None",
      "io_time_recursive":"None",
      "sectors_recursive":"None"
   },
   "num_procs":0,
   "storage_stats":{
      
   },
   "cpu_stats":{
      "cpu_usage":{
         "total_usage":7663009467000,
         "usage_in_kernelmode":2482186707000,
         "usage_in_usermode":5180822760000
      },
      "system_cpu_usage":8698570140000000,
      "online_cpus":4,
      "throttling_data":{
         "periods":0,
         "throttled_periods":0,
         "throttled_time":0
      }
   },
   "precpu_stats":{
      "cpu_usage":{
         "total_usage":7663006919000,
         "usage_in_kernelmode":2482185881000,
         "usage_in_usermode":5180821037000
      },
      "system_cpu_usage":8698566120000000,
      "online_cpus":4,
      "throttling_data":{
         "periods":0,
         "throttled_periods":0,
         "throttled_time":0
      }
   },
   "memory_stats":{
      "usage":48582656,
      "stats":{
         "active_anon":7131136,
         "active_file":7737344,
         "anon":35463168,
         "anon_thp":0,
         "file":10469376,
         "file_dirty":0,
         "file_mapped":8818688,
         "file_writeback":0,
         "inactive_anon":26853376,
         "inactive_file":4218880,
         "kernel_stack":458752,
         "pgactivate":22237,
         "pgdeactivate":19513,
         "pgfault":1092850,
         "pglazyfree":23672,
         "pglazyfreed":7507,
         "pgmajfault":1005,
         "pgrefill":37657,
         "pgscan":41681,
         "pgsteal":17236,
         "shmem":315392,
         "slab":1461560,
         "slab_reclaimable":972816,
         "slab_unreclaimable":488744,
         "sock":16384,
         "thp_collapse_alloc":0,
         "thp_fault_alloc":0,
         "unevictable":0,
         "workingset_activate":0,
         "workingset_nodereclaim":0,
         "workingset_refault":0
      },
      "limit":16420589568
   },
   "name":"/nginx-proxy",
   "id":"05c17d2577221a9e0e2fe3ebc1069879a601ba09a6f03bf9b7884d4592fef460",
   "networks":{
      "eth0":{
         "rx_bytes":897265101,
         "rx_packets":1708810,
         "rx_errors":0,
         "rx_dropped":0,
         "tx_bytes":1186535007,
         "tx_packets":1629835,
         "tx_errors":0,
         "tx_dropped":0
      }
   }
}
```

**Comment by atommaki** [comment]
I replaced the "rss" to "usage", now it should work. However it is not clean for me what is reported as "usage" and why the "rss" is not there any more.
